version: 1.0.{build}
image: Visual Studio 2022
branches:
  only:
    - main
environment:
  deploy_username:
    secure: ZumRpgIeGcRgW3H7yXK0bQ==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
  deploy_publish_url:
    secure: QIYfGJ1+d6VJ/xxUp/T7jOvzBVGPfFZC6UFYz08nIysGHmgjF5zU9SQvcl5tbJ2RHK5W9/IgBuv1aJNx09G1bvBM4UsKzfR+4snDUvdXKuvuLIq95yZxXJKV4ewT6h30OsfWxwKTb1JNGzhxmPVneagSB6bDwYcJ81wINqyRIDI=
  ms_deploy_site:
    secure: be3uht79X/eogI8gd1fkRot7sd9NQFxU/riUI8GPYZ7DDOr06EW2aTUpoxwDTi7q
  db_server:
    secure: GENtSiIHJlcMVdOs9CjeQw==
  db_name:
    secure: hHBJ3rJzhyAeewNTWR9Cwg==
  db_username:
    secure: hHBJ3rJzhyAeewNTWR9Cwg==
  db_password:
    secure: SFAvHfsz398LTl83QbS5gw==
  clave_secreta_jwt:
    secure: D7/n0u0zIlvANO9rI/Wn0FFpipPrMJihdNGClSAG+oH6N7jm2EaAbD++QFAbCXGgT/Ixsp+T+KAm/qEd/OTS6jiTOXx21PFSj3c6zdvB1Fuldb9LwgMZ/3vF2UCSgUMtWHu1KJikA2pY0F++TRteBlnnerbxxBNZP5QlaCVn6js=
install:
  - ps: >-
      $file = "./Api/appsettings.Production.json";
      (Get-Content $file).Replace("{db_server}", $env:db_server).Replace("{db_name}", $env:db_name).Replace("{db_username}", $env:db_username).Replace("{db_password}", $env:db_password).Replace("{clave_secreta_jwt}", $env:clave_secreta_jwt) | Set-Content $file
build_script:
  - cmd: dotnet publish --framework net8.0 /p:EnvironmentName=Production --self-contained true -r win-x64 Api --output %appveyor_build_folder%\dist
test_script:
  # Ejecuta tests
  - dotnet test --configuration Release --runtime win-x64
before_deploy:
  # Aplica migraciones pendientes
  - cd Api
  - dotnet tool install dotnet-ef --global --version 8.0.0
  - ps: $DefaultConnectionString = (Get-Content appsettings.Production.json | ConvertFrom-Json).ConnectionStrings.Default
  - ps: dotnet ef database update --connection $DefaultConnectionString
artifacts:
  - path: dist
deploy:
  - provider: WebDeploy
    remove_files: true
    skip_dirs: \\App_Data;\\Imagenes;\\logs;\\aspnet_client;\\wwwroot;\\well-known;
    server: $(deploy_publish_url)
    website: $(ms_deploy_site)
    username: $(deploy_username)
    password: $(deploy_password)
    ntlm: false
    app_offline: true
    sync: true
