// <auto-generated />
using System;
using Api.Persistencia._Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701211909_AgregaSincronizacionObjetivosHabitos")]
    partial class AgregaSincronizacionObjetivosHabitos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Core.Entidades.Carpeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CarpetaPadreId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CriterioDeOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<int?>("PropositoCarpeta")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereAutenticacion")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaPadreId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("CriterioDeOrdenId");

                    b.ToTable("Carpetas");
                });

            modelBuilder.Entity("Api.Core.Entidades.ContadorSync", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("UltimoValor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ContadoresSync");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UltimoValor = 0L
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.CriterioDeOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CriterioDeOrden");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Criterio = "Creación Desc"
                        },
                        new
                        {
                            Id = 2,
                            Criterio = "Edición Desc"
                        },
                        new
                        {
                            Id = 3,
                            Criterio = "A-Z"
                        },
                        new
                        {
                            Id = 4,
                            Criterio = "Creación Asc"
                        },
                        new
                        {
                            Id = 5,
                            Criterio = "Edición Asc"
                        },
                        new
                        {
                            Id = 6,
                            Criterio = "Z-A"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.Escrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarpetaId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cuerpo")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaEnPapelera")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraEdicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Escritos");
                });

            modelBuilder.Entity("Api.Core.Entidades.Habito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MetaMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Habitos");
                });

            modelBuilder.Entity("Api.Core.Entidades.ItemObjetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListaObjetivoId")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("ListaObjetivoId");

                    b.ToTable("ItemsObjetivo");
                });

            modelBuilder.Entity("Api.Core.Entidades.ListaObjetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClavePeriodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("Tipo", "ClavePeriodo")
                        .IsUnique();

                    b.ToTable("ListasObjetivo");
                });

            modelBuilder.Entity("Api.Core.Entidades.RegistroHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitoId")
                        .HasColumnType("int");

                    b.Property<bool?>("ValorBooleano")
                        .HasColumnType("bit");

                    b.Property<int?>("ValorNumerico")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("HabitoId", "Fecha")
                        .IsUnique();

                    b.ToTable("RegistrosHabito");
                });

            modelBuilder.Entity("Api.Core.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        });
                });

            modelBuilder.Entity("Api.Core.Entidades.SyncOpLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientOpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProcesadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOpId")
                        .IsUnique();

                    b.ToTable("SyncOpLogs");
                });

            modelBuilder.Entity("Api.Core.Entidades.Tombstone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EliminadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Version");

                    b.ToTable("Tombstones");
                });

            modelBuilder.Entity("Api.Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Api.Core.Entidades.Carpeta", b =>
                {
                    b.HasOne("Api.Core.Entidades.Carpeta", "CarpetaPadre")
                        .WithMany("SubCarpetas")
                        .HasForeignKey("CarpetaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Core.Entidades.CriterioDeOrden", "CriterioDeOrden")
                        .WithMany("Carpetas")
                        .HasForeignKey("CriterioDeOrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarpetaPadre");

                    b.Navigation("CriterioDeOrden");
                });

            modelBuilder.Entity("Api.Core.Entidades.Escrito", b =>
                {
                    b.HasOne("Api.Core.Entidades.Carpeta", "Carpeta")
                        .WithMany("Escritos")
                        .HasForeignKey("CarpetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carpeta");
                });

            modelBuilder.Entity("Api.Core.Entidades.ItemObjetivo", b =>
                {
                    b.HasOne("Api.Core.Entidades.ListaObjetivo", "ListaObjetivo")
                        .WithMany("Items")
                        .HasForeignKey("ListaObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaObjetivo");
                });

            modelBuilder.Entity("Api.Core.Entidades.RegistroHabito", b =>
                {
                    b.HasOne("Api.Core.Entidades.Habito", "Habito")
                        .WithMany("Registros")
                        .HasForeignKey("HabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");
                });

            modelBuilder.Entity("Api.Core.Entidades.Usuario", b =>
                {
                    b.HasOne("Api.Core.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Api.Core.Entidades.Carpeta", b =>
                {
                    b.Navigation("Escritos");

                    b.Navigation("SubCarpetas");
                });

            modelBuilder.Entity("Api.Core.Entidades.CriterioDeOrden", b =>
                {
                    b.Navigation("Carpetas");
                });

            modelBuilder.Entity("Api.Core.Entidades.Habito", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Api.Core.Entidades.ListaObjetivo", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
